api_platform:
    title: 'Lilou draws'
    description: 'Api for Lilou draws, only for admins'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
